version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpack:
    image: node:12.14
    command: bash -c "yarn install && yarn start"
    depends_on:
      - app
    working_dir: "/app"
    volumes:
      - .:/app
    ports:
      - "3500:3500"
